LCesarAdvogados.MVC/Controllers/PostsController.cs
using AutoMapper;
using LCesarAdvogados.Aplicacao.Interface;
using LCesarAdvogados.Dominio.Entidades;
using LCesarAdvogados.MVC.ViewModel;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace LCesarAdvogados.MVC.Controllers
{
    public class PostsController : Controller
    {
      
        private readonly IPostAppServicos _PostAplicacao;
        public PostsController(IPostAppServicos PostAplicacao)
        {
            _PostAplicacao = PostAplicacao;
        }

        public ActionResult Index()
        {
            var PostViewModel = Mapper.Map<IEnumerable<Posts>, IEnumerable<PostViewModel>>(_PostAplicacao.GetAll());
            return View(PostViewModel);
        }

        public ActionResult Details(int id)
        {
            return View();
        }

        public ActionResult Create()
        {
            return View();
        }
     
        [HttpPost]
        public ActionResult Create(PostViewModel post, HttpPostedFileBase file)
        {
            var errors = ModelState.Values.SelectMany(v => v.Errors);          
            try
            {
                if (file.ContentLength > 0)
                {
                    var fileName = Path.GetFileName(file.FileName);
                    var path = Path.Combine(Server.MapPath("~/img/Posts"), fileName);
                    file.SaveAs(path);
                    post.ImagemPost = "../img/Posts/" + fileName;
                }
                var PostDominio = Mapper.Map<PostViewModel, Posts>(post);
                _PostAplicacao.Add(PostDominio);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        public ActionResult Edit(int id)
        {
            var Post = _PostAplicacao.GetById(id);
            var PostsViewModel = Mapper.Map<Posts, PostViewModel>(Post);

            return View(PostsViewModel);
        }

        [HttpPost]
        public ActionResult Edit(PostViewModel Post)
        {
            try
            {
                var PostDomain = Mapper.Map<PostViewModel, Posts>(Post);
                _PostAplicacao.Update(PostDomain);
                return RedirectToAction("Index");
            }
            catch
            {

            }
            return View(Post);
        }

        public ActionResult Delete(int id)
        {
            var Posts = _PostAplicacao.GetById(id);
            var PostViewModel = Mapper.Map<Posts, PostViewModel>(Posts);

            return View(PostViewModel);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id, FormCollection collection)
        {
            var Post = _PostAplicacao.GetById(id);
            _PostAplicacao.Remove(Post);

            return RedirectToAction("Index");
        }
    }
}

LCesarAdvogados.MVC/Controllers/UsuariosController.cs
using AutoMapper;
using LCesarAdvogados.Aplicacao.Interface;
using LCesarAdvogados.Dominio.Entidades;
using LCesarAdvogados.MVC.Filtros;
using LCesarAdvogados.MVC.ViewModel;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace LCesarAdvogados.MVC.Controllers
{
   //[AutorizacaoFilterAttribute]
    public class UsuariosController : Controller
    {
        private readonly IUsuarioAppServico _UsuarioAplicacao;
        public UsuariosController(IUsuarioAppServico UsuarioAplicacao)
        {
            _UsuarioAplicacao = UsuarioAplicacao;
        }
        public ActionResult Index()
        {
            var UsuarioViewModel = Mapper.Map<IEnumerable<Usuario>, IEnumerable<UsuarioViewModel>>(_UsuarioAplicacao.GetAll());
            return View(UsuarioViewModel);
        }

        public ActionResult Details(int id)
        {
            return View();
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(UsuarioViewModel usuario)
        {
            var errors = ModelState.Values.SelectMany(v => v.Errors);
            try
            {
                var UsuarioDominio = Mapper.Map<UsuarioViewModel, Usuario>(usuario);
                _UsuarioAplicacao.Add(UsuarioDominio);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Edit(int id)
        {
            var Usuario = _UsuarioAplicacao.GetById(id);
            var UsuarioViewModel = Mapper.Map<Usuario, UsuarioViewModel>(Usuario);

            return View(UsuarioViewModel);
        }

        [HttpPost]
        public ActionResult Edit(UsuarioViewModel Usuario)
        {
            try
            {              
                    var UsuarioDomain = Mapper.Map<UsuarioViewModel, Usuario>(Usuario);
                    _UsuarioAplicacao.Update(UsuarioDomain);
                    return RedirectToAction("Index");                
            }
            catch
            {

            }
            return View(Usuario);
        }

        public ActionResult Delete(int id)
        {
            var Usuario = _UsuarioAplicacao.GetById(id);
            var UsuarioViewModel = Mapper.Map<Usuario, UsuarioViewModel>(Usuario);

            return View(UsuarioViewModel);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var Usuario = _UsuarioAplicacao.GetById(id);
            _UsuarioAplicacao.Remove(Usuario);

            return RedirectToAction("Index");
        }
    }
}

LCesarAdvogados.MVC/Views/Posts/Create.cshtml
@model LCesarAdvogados.MVC.ViewModel.PostViewModel

@{
    ViewBag.Title = "LCesar Advogados";
    Layout = "~/Views/Shared/AreaAdmin.cshtml";
}
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<link href="~/Content/bootstrap.css" rel="stylesheet" />
<script src="~/Scripts/SummerNote/summernote.js"></script>
<link href="~/Scripts/SummerNote/summernote.css" rel="stylesheet" />
<script src="~/Scripts/Post.js"></script>

@using (Html.BeginForm("Create",
                        "Posts",  
                        FormMethod.Post,  
                        new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        @Html.ValidationSummary(true)
        <div class="form-group">
            <div class="col-md-12">
                @Html.LabelFor(model => model.TituloPost, new { @class = "control-label" })
                @Html.TextBoxFor(model => model.TituloPost, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TituloPost, null, new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-12">               
                <label for="file">Imagem do Resumo:</label>
                <input type="file" name="file" id="file" />      
            </div>
        </div>   
        <div class="form-group">
            <div class="col-md-12">
                @Html.LabelFor(model => model.ResumoPost, new { @class = "control-label" })
                @Html.TextAreaFor(model => model.ResumoPost, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ResumoPost, null, new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-12">               
                @Html.LabelFor(model => model.ConteudoPost, new { @class = "control-label" })
                @Html.TextAreaFor(model => model.ConteudoPost)
                @Html.ValidationMessageFor(model => model.ConteudoPost, null, new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-12 col-xs-12 col-sm-12 col-lg-12">
                <input type="submit" value="Salvar" class="btn btn-primary" />
                <a href="@Url.Action("Index", "Usuarios")" class="btn btn-default">Voltar</a>
            </div>
        </div>
    </div>
}

LCesarAdvogados.MVC/Views/Posts/Delete.cshtml
@model LCesarAdvogados.MVC.ViewModel.PostViewModel

@{
    ViewBag.Title = "LCesar Advogados";
    Layout = "~/Views/Shared/AreaAdmin.cshtml";
}

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="~/Content/bootstrap.css" rel="stylesheet" />

    <style>
        .trCabecalho {
            background-color: #2A3F54;
            color: #fff;
            width:15%!important;
        }

        .trCorpo {
            background-color: #f5f5f5;
        }
    </style>
</head>
<link href="~/Content/bootstrap.css" rel="stylesheet" />
<body style="background-color:#fff!important">
    <h3>Tem certeza que deseja excluir este Post?</h3>
    <div>
        <table class="table table-bordered">
            <tr>
                <td class="trCabecalho">
                  Id
                </td>

                <td class="trCorpo">
                    @Html.DisplayFor(model => model.IdPost)
                </td>
            </tr>
            <tr>
                <td class="trCabecalho">
                  Título
                </td>
                <td class="trCorpo">
                    @Html.DisplayFor(model => model.TituloPost)
                </td>

            </tr> 
            <tr>
                <td class="trCabecalho">
                    Data Cadastro
                </td>
                <td class="trCorpo">
                    @Html.DisplayFor(model => model.DataCadastro)
                </td>
            </tr>          
        </table>
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            <div class="form-actions no-color">
                <input type="submit" value="Excluir" class="btn btn-primary" />
                <a href="@Url.Action("Index", "Posts")" class="btn btn-default">Voltar</a>
            </div>
        }
    </div>
</body>

LCesarAdvogados.MVC/Views/Posts/Edit.cshtml
@model LCesarAdvogados.MVC.ViewModel.PostViewModel

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/AreaAdmin.cshtml";
}
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<link href="~/Content/bootstrap.css" rel="stylesheet" />
<script src="~/Scripts/SummerNote/summernote.js"></script>
<link href="~/Scripts/SummerNote/summernote.css" rel="stylesheet" />
<script src="~/Scripts/Post.js"></script>

<body style="background-color:#fff!important">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div class="form-horizontal">
            @Html.ValidationSummary(true)
            @Html.HiddenFor(model => model.IdPost)
            <div class="form-group">
                <div class="col-md-12 col-xs-12 col-sm-12 col-lg-12">
                    @Html.LabelFor(model => model.TituloPost, new { @class = "control-label" })
                    @Html.TextBoxFor(model => model.TituloPost, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.TituloPost ,null, new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-12 col-xs-12 col-sm-12 col-lg-12">
                    @Html.LabelFor(model => model.ResumoPost, new { @class = "control-label" })
                    @Html.TextAreaFor(model => model.ResumoPost,new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.ResumoPost, null, new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-12 col-xs-12 col-sm-12 col-lg-12">
                    @Html.LabelFor(model => model.ConteudoPost, new { @class = "control-label" })
                    @Html.TextAreaFor(model => model.ConteudoPost)
                    @Html.ValidationMessageFor(model => model.ConteudoPost, null, new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-12 col-xs-12 col-sm-12 col-lg-12">
                    <input type="submit" value="Salvar" class="btn btn-primary" />
                    <a href="@Url.Action("Index", "Posts")" class="btn btn-default">Voltar</a>
                </div>
            </div>
        </div>
    }
</body>

LCesarAdvogados.MVC/Views/Posts/Index.cshtml
@model IEnumerable<LCesarAdvogados.MVC.ViewModel.PostViewModel>

@{
    ViewBag.Title = "LCesar Advogados";
    Layout = "~/Views/Shared/AreaAdmin.cshtml";
}
<link href="~/Content/bootstrap.css" rel="stylesheet" />
<link href="~/Content/AreaAdmin/Usuarios.css" rel="stylesheet" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.min.js"></script>

<html>
<head>
    <style class="cp-pen-styles">
        .divtable .tr {
            overflow: hidden;
            clear: both;
            border-bottom: 1px solid #ccc;
        }

        .divtable .th,
        .divtable .td {
            padding: 5px 10px;
            float: left;
        }

        .divtable .th {
            font-weight: bold;
        }

        .Titulo {
            width: 70%;
        }

        .Data {
            width: 20%;
        }

        .Acao {
            width: 10%;
        }

        @@media (max-width: 767px) {
            .accordion-xs .headings {
                display: none;
            }

            .accordion-xs .tr {
                border-bottom-color: #fff;
            }

            .accordion-xs .th,
            .accordion-xs .td {
                float: none;
                width: auto;
                padding: 0;
            }

            .accordion-xs .accordion-xs-toggle {
                background-color: #2A3F54;
                color: #fff;
                padding: 10px;
                cursor: pointer;
            }

                .accordion-xs .accordion-xs-toggle:hover {
                    background-color: rgba(42, 63, 84, 0.75);
                }

                .accordion-xs .accordion-xs-toggle:after {
                    content: '\2b';
                    float: right;
                }

                .accordion-xs .accordion-xs-toggle.collapsed:after {
                    content: '\2212';
                }

            .accordion-xs-collapse .inner {
                padding: 10px;
            }

            .accordion-xs-collapse .td:before {
                font-weight: bold;
            }


            .accordion-xs-collapse .Data:before {
                content: 'Data: ';
            }

            .accordion-xs-collapse .Acao:before {
                content: 'Ação: ';
            }

            .accordion-xs .accordion-xs-toggle:after {
                position: relative;
                top: 1px;
                display: inline-block;
                font-family: 'Glyphicons Halflings';
                font-style: normal;
                font-weight: 400;
                line-height: 1;
                -webkit-font-smoothing: antialiased;
            }
        }
    </style>
</head>
<body style="background-color:#fff!important">
    <div class="divtable accordion-xs">
        <div class="tr headings" style="background-color: #2A3F54;color:#fff">
            <div class="th Titulo">Titulo</div>
            <div class="th Data">Data</div>
            <div class="th Acao">Ação</div>
        </div>
        @foreach (var item in Model)
            {
            <div class="tr table-striped">
                <div class="td Titulo accordion-xs-toggle">@Html.DisplayFor(modelItem => item.TituloPost)</div>
                <div class="accordion-xs-collapse">
                    <div class="inner">
                        <div class="td Data">@Html.DisplayFor(modelItem => item.DataCadastro)</div>
                        <div class="th Acao">
                            <a href="@Url.Action("Edit", "Posts", new { id = item.IdPost})"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a> |
                            <a href="@Url.Action("Delete", "Posts", new { id = item.IdPost})"><i class="fa fa-trash-o" aria-hidden="true"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
    <br>
    <a href="@Url.Action("Create", "Posts")" class="btn btn-primary">Novo Post</a>
    <script src="http://code.jquery.com/jquery-1.11.2.min.js"></script>
    <script src="http://netdna.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
    <script>
        $(function () {
            var isXS = false,
                $accordionXSCollapse = $('.accordion-xs-collapse');

            // Window resize event (debounced)
            var timer;
            $(window).resize(function () {
                if (timer) { clearTimeout(timer); }
                timer = setTimeout(function () {
                    isXS = Modernizr.mq('only screen and (max-width: 767px)');

                    // Add/remove collapse class as needed
                    if (isXS) {
                        $accordionXSCollapse.addClass('collapse');
                    } else {
                        $accordionXSCollapse.removeClass('collapse');
                    }
                }, 100);
            }).trigger('resize'); //trigger window resize on pageload

            // Initialise the Bootstrap Collapse
            $accordionXSCollapse.each(function () {
                $(this).collapse({ toggle: false });
            });

            // Accordion toggle click event (live)
            $(document).on('click', '.accordion-xs-toggle', function (e) {
                e.preventDefault();

                var $thisToggle = $(this),
                    $targetRow = $thisToggle.parent('.tr'),
                    $targetCollapse = $targetRow.find('.accordion-xs-collapse');

                if (isXS && $targetCollapse.length) {
                    var $siblingRow = $targetRow.siblings('.tr'),
                        $siblingToggle = $siblingRow.find('.accordion-xs-toggle'),
                        $siblingCollapse = $siblingRow.find('.accordion-xs-collapse');

                    $targetCollapse.collapse('toggle'); //toggle this collapse
                    $siblingCollapse.collapse('hide'); //close siblings

                    $thisToggle.toggleClass('collapsed'); //class used for icon marker
                    $siblingToggle.removeClass('collapsed'); //remove sibling marker class
                }
            });
        });
    </script>
    <script type="text/javascript">
        var _gaq = _gaq || [];
        _gaq.push(['_setAccount', 'UA-36251023-1']);
        _gaq.push(['_setDomainName', 'jqueryscript.net']);
        _gaq.push(['_trackPageview']);

        (function () {
            var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
            ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
        })();

    </script>
</body>
</html>