LCesarAdvogados.MVC/Controllers/VisualizaPostController.cs
using AutoMapper;
using LCesarAdvogados.Aplicacao.Interface;
using LCesarAdvogados.Dominio.Entidades;
using LCesarAdvogados.MVC.ViewModel;
using System.Collections.Generic;
using System.Web.Mvc;

namespace LCesarAdvogados.MVC.Controllers
{
    public class VisualizaPostController : Controller
    {
        
        private readonly IPostAppServicos _PostAplicacao;
        public VisualizaPostController(IPostAppServicos PostAplicacao)
        {
            _PostAplicacao = PostAplicacao;
        }
        public ActionResult Index()
        {
            var VisualizaPostViewModel = Mapper.Map<IEnumerable<Posts>, IEnumerable<PostViewModel>>(_PostAplicacao.GetAll());
            return View(VisualizaPostViewModel);  
        }
        public ActionResult GetForId(int id)
        {
            ViewData["IdPost"] = id;
            var VisualizaPostViewModelID = Mapper.Map<Posts, PostViewModel>(_PostAplicacao.GetById(id));

            if (VisualizaPostViewModelID != null)
                return View(VisualizaPostViewModelID);
            else
                return RedirectToAction("index");
        }

        public ActionResult Details(int id)
        {
            return View();
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
 
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Edit(int id)
        {
            return View();
        }

        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult Delete(int id)
        {
            return View();
        }

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

LCesarAdvogados.MVC/Views/VisualizaPost/GetForId.cshtml
@model LCesarAdvogados.MVC.ViewModel.PostViewModel

@{
    Layout = null;
}

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<link rel="stylesheet" href="~/Content/VisualizaPost/VisualizaPost.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

<nav class="navbar navbar-default navbar-fixed-top navbar-inverse">
    <div class="container">
        <div class="navbar-header">
            <a class="navbar-brand" href="@Url.Action("Index", "Home")">
                L.CÉSAR Advogados
            </a>
        </div>
    </div>
</nav>
<div class="container" style="margin-top:50px">
    <div class="row col-sm-12 SeparaDiv">
        <div class="col-sm-12"><h1>@Html.DisplayFor(modelItem => Model.TituloPost)</h1></div>
        <div class="col-sm-12">@Html.Raw(HttpUtility.HtmlDecode(Model.ConteudoPost))</div>
    </div>
    <div>
        <a href="@Url.Action("Index", "VisualizaPost")" target="_self" class="btn btn-primary OutrasNoticias">Outras Notícias</a>
    </div>
</div>

LCesarAdvogados.MVC/Views/VisualizaPost/Index.cshtml
@model IEnumerable<LCesarAdvogados.MVC.ViewModel.PostViewModel>

@{
    ViewBag.Title = "LCesar Advogados";
    Layout = null;
}
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<style>
    .SeparaDiv {
        border-bottom: 5px solid #000;
        padding-bottom: 50px;
    }
</style>
<nav class="navbar navbar-default navbar-fixed-top navbar-inverse">
    <div class="container">
        <div class="navbar-header">
            <a class="navbar-brand" href="@Url.Action("Index", "Home")">
                L.CÉSAR Advogados
            </a>
        </div>
    </div>
</nav>
<div class="container" style="margin-top:50px">
    @foreach (var item in Model)
    {
            <div class="row col-sm-12 SeparaDiv">
                <div class="col-sm-12"><h1>@Html.DisplayFor(modelItem => item.TituloPost)</h1></div>
                <div class="col-sm-12">@Html.Raw(HttpUtility.HtmlDecode(item.ConteudoPost))</div>
            </div>
    }
</div>